Checks if dtc-xen-parse-param is accessible and readable, exit if not. Thanks to Rubén Mediano <rmediano@hienipa.com>

diff --git a/src/dtc-xen_domUconf_standard b/src/dtc-xen_domUconf_standard
--- a/src/dtc-xen_domUconf_standard
+++ b/src/dtc-xen_domUconf_standard
@@ -2,7 +2,15 @@
 
 # This script is shared by almost all Unix distributions, it's a good idea to call it.
 
-. /usr/share/dtc-xen/dtc-xen-parse-param
+if [ -r /usr/share/dtc-xen/dtc-xen-parse-param ]; then
+       . /usr/share/dtc-xen/dtc-xen-parse-param
+else
+       echo "Fatal Error: Cannot read file /usr/share/dtc-xen/dtc-xen-parse-param. Exiting ..." && exit 1
+fi
+
+if [ "x$VPS_PATH" = "x" ]; then
+       echo "Fatal Error: $VPS_PATH is not defined or empty. Exiting ..." && exit 1
+fi
 
 ETC=${VPS_PATH}/etc
 
