Added a chpass call to set the VPS root password, thanks to Rubén Mediano <rmediano@hienipa.com>

diff --git a/src/dtc_reinstall_os b/src/dtc_reinstall_os
--- a/src/dtc_reinstall_os
+++ b/src/dtc_reinstall_os
@@ -568,6 +568,15 @@ else
 	fi
 fi
 
+echo -n "Setting root password... "
+chroot ${VPSGLOBPATH}/${VPSNUM} sh -c "echo root:$PASSWORD | chpasswd"
+
+if [ $? -eq 0 ] ; then
+    echo "[OK]"
+else
+    echo "[FAIL]"
+fi
+
 ####################################
 ### NETWORK CONFIG CUSTOMIZATION ###
 ####################################
