Auto-detection of the volume group to provision disk space, complete

diff --git a/src/dtc_change_bsd_kernel b/src/dtc_change_bsd_kernel
--- a/src/dtc_change_bsd_kernel
+++ b/src/dtc_change_bsd_kernel
@@ -10,6 +10,14 @@ fi
 # Source the configuration in the config file!
 . /etc/dtc-xen/dtc_create_vps.conf.sh
 
+# Figure out the LVM name from dtc-xen.conf
+LVMNAME=`dtc-xen-volgroup`
+[ -z "$LVMNAME" ] && {
+	echo "Could not determine volume group from which to provision the volume" 1>&2
+	echo "You might want to set provisioning_volgroup in dtc-xen.conf" 1>&2
+	exit 78
+}
+
 #NODE_NUM=6501
 #DEBIAN_REPOS="http://65.apt-proxy.gplhost.com:9999/debian"
 #NETMASK=255.255.255.0
@@ -18,7 +26,6 @@ fi
 #GATEWAY=202.124.18.1
 
 # Things that might change
-if [ "$LVMNAME" = "" ] ; then LVMNAME=lvm1 ; fi
 VPSGLOBPATH=${VPS_MOUNTPOINT}
 #KERNELNAME="2.6.11.12-xenU"
 INSTALL_KERNELPATH="/boot/netbsd-INSTALL_XENU"
diff --git a/src/dtc_kill_vps_disk b/src/dtc_kill_vps_disk
--- a/src/dtc_kill_vps_disk
+++ b/src/dtc_kill_vps_disk
@@ -11,7 +11,6 @@ fi
 . /etc/dtc-xen/dtc_create_vps.conf.sh
 
 # Things that might change
-# LVMNAME=lvm1
 VPSGLOBPATH=${VPS_MOUNTPOINT}
 
 # Things that most of then time don't change
@@ -19,6 +18,18 @@ VPSNUM=$1
 VPSNAME=xen${VPSNUM}
 VPSHOSTNAME=xen${NODE_NUM}${VPSNUM}
 IMAGE_TYPE=$2
+
+[ -z "$IMAGE_TYPE" ] && IMAGE_TYPE=lvm
+
+# Figure out the LVM name from dtc-xen.conf
+if [ "$IMAGE_TYPE" = "lvm" ] ; then
+	LVMNAME=`dtc-xen-volgroup`
+	[ -z "$LVMNAME" ] && {
+		echo "Could not determine volume group from which to provision the volume" 1>&2
+		echo "You might want to set provisioning_volgroup in dtc-xen.conf" 1>&2
+		exit 78
+	}
+fi
 
 # redirect stdout and stderr to log files, so we can see what happened during install
 
diff --git a/src/dtc_reinstall_os b/src/dtc_reinstall_os
--- a/src/dtc_reinstall_os
+++ b/src/dtc_reinstall_os
@@ -35,8 +35,8 @@ fi
 
 # Source the configuration in the config file!
 . /etc/dtc-xen/dtc_create_vps.conf.sh
+
 # Some defaults if not present in the conf file...
-if [ "$LVMNAME" = "" ] ; then LVMNAME=lvm1 ; fi
 if [ "$DEBIAN_RELEASE" = "" ] ; then DEBIAN_RELEASE=etch ; fi
 
 # Manage options in any order...
@@ -103,6 +103,18 @@ PASSWORD=$5
 DISTRO=$6
 IMAGE_TYPE=$7
 
+[ -z "$IMAGE_TYPE" ] && IMAGE_TYPE=lvm
+
+# Figure out the LVM name from dtc-xen.conf
+if [ "$IMAGE_TYPE" = "lvm" ] ; then
+	LVMNAME=`dtc-xen-volgroup`
+	[ -z "$LVMNAME" ] && {
+		echo "Could not determine volume group from which to provision the volume" 1>&2
+		echo "You might want to set provisioning_volgroup in dtc-xen.conf" 1>&2
+		exit 78
+	}
+fi
+
 # Configure the first IP only (the user can setup the others)
 IPADDR=`echo ${ALL_IPADDRS} | cut -d' ' -f1`
 
@@ -120,12 +132,6 @@ calcMacAddr () {
 	MAC_ADDR=`echo 00:00:2$MEGA_NUM:$MAJOR_NUM:$MINOR_NUM:$VPSNUM`
 }
 calcMacAddr
-
-# default to lvm type for backwards compatibility
-if [ -z "$IMAGE_TYPE" ]; then
-	IMAGE_TYPE=lvm
-fi
-
 
 FOUNDED_ARCH=`uname -m`
 
diff --git a/src/dtc_setup_vps_disk b/src/dtc_setup_vps_disk
--- a/src/dtc_setup_vps_disk
+++ b/src/dtc_setup_vps_disk
@@ -2,7 +2,7 @@
 
 if [ $# -lt 3 ]; then 
 	echo "Usage: $0 <xen id> <hdd size> <swap size> [lvm/vbd]"
-	exit
+	exit 64
 fi
 
 # Things that often change
@@ -11,7 +11,6 @@ fi
 . /etc/dtc-xen/dtc_create_vps.conf.sh
 
 # Things that might change
-# LVMNAME=lvm1
 VPSGLOBPATH=${VPS_MOUNTPOINT}
 
 # Things that most of then time don't change
@@ -21,6 +20,18 @@ VPSHOSTNAME=xen${NODE_NUM}${VPSNUM}
 VPSHDD=$2
 VPSMEM=$3
 IMAGE_TYPE=$4
+
+[ -z "$IMAGE_TYPE" ] && IMAGE_TYPE=lvm
+
+# Figure out the LVM name from dtc-xen.conf
+if [ "$IMAGE_TYPE" = "lvm" ] ; then
+	LVMNAME=`dtc-xen-volgroup`
+	[ -z "$LVMNAME" ] && {
+		echo "Could not determine volume group from which to provision the volume" 1>&2
+		echo "You might want to set provisioning_volgroup in dtc-xen.conf" 1>&2
+		exit 78
+	}
+fi
 
 # redirect stdout and stderr to log files, so we can see what happened during install
 
@@ -36,10 +47,6 @@ fi
 exec 1>$VPSGLOBPATH/$VPSNUM.setuplvm.stdout
 exec 2>$VPSGLOBPATH/$VPSNUM.setuplvm.stderr
 
-
-if [ -z ""$IMAGE_TYPE ]; then
-	IMAGE_TYPE=lvm
-fi
 
 LVCREATE=/sbin/lvcreate
 LVREMOVE=/sbin/lvremove
diff --git a/src/dtc_write_xenpv_conf b/src/dtc_write_xenpv_conf
--- a/src/dtc_write_xenpv_conf
+++ b/src/dtc_write_xenpv_conf
@@ -12,7 +12,14 @@ fi
 # Source the configuration in the config file!
 . /etc/dtc-xen/dtc_create_vps.conf.sh
 
-if [ "$LVMNAME" = "" ] ; then LVMNAME=lvm1 ; fi
+LVMNAME=`dtc-xen-volgroup`
+[ -z "$LVMNAME" ] && {
+	echo "Could not determine volume group from which to provision the volume" 1>&2
+	echo "You might want to set provisioning_volgroup in dtc-xen.conf" 1>&2
+	exit 78
+}
+
+
 VPSGLOBPATH=${VPS_MOUNTPOINT}
 INSTALL_KERNELPATH="/boot/netbsd-INSTALL_XENU"
 NORMAL_KERNELPATH="/boot/netbsd-XENU"
